### ISSUE TITLE
Where to input OpenAI API Key?

### ISSUE THREAD

**Issue by enzyme69** [gd3kr/BlenderGPT#1]
Where do we actually set as an environment variable OPENAI_API_KEY? Would be nice if the option is in the addon setting.

**Comment by Ethaisa123** [comment]
you have to extract the file and then open __init___.py 
then go to line 13 `openai.api_key = os.getenv("OPENAI_API_KEY")
`then replace OPENAI_API_KEY with your openai key from the openai website
![image](https://user-images.githubusercontent.com/100451791/226765050-c24f1247-32e1-41c6-99f8-da645c461b35.png)

**Comment by enzyme69** [comment]
I tried adding the OPENAI_API_KEY into that line but still failing to work:
![Screenshot 2023-03-22 at 10 52 02 am](https://user-images.githubusercontent.com/3952687/226767218-18ae9c9c-25f1-45a9-b3da-15da72b6f5b9.png)

**Comment by gd3kr** [comment]
Fixed in the latest release. Now you can set the OpenAI API key directly in the UI under the addon preferences!
![sc](https://user-images.githubusercontent.com/63528145/226786327-781782d7-f114-40d8-bc56-668f710f87e3.png)

**Comment by enzyme69** [comment]
Thanks I will give it a try
