### ISSUE TITLE
Add Option to Choose Model: ChatGPT Turbo vs GPT-4

### ISSUE THREAD

**Issue by VertexMachine** [gd3kr/BlenderGPT#16]
Currently, the default model is GPT-4, which is slower and more expensive than other available models. In my experience, ChatGPT Turbo performs comparably for various tasks but at a fraction of the cost (10x cheaper) and with significantly faster response times.

I propose adding an option for users to choose their preferred AI model when using the add-on. This feature will enable users to select between ChatGPT Turbo and GPT-4, depending on their needs and budget. By providing this choice, users can optimize their experience based on speed, cost, and performance considerations.

**Comment by gd3kr** [comment]
100%. This will be an option in ~1 day
