### ISSUE TITLE
"Failed to generate Blender Python code"

### ISSUE THREAD

**Issue by Shraknard** [gd3kr/BlenderGPT#2]
Couldn't make it works. After adding the API_KEY, I get a "***Failed to generate Blender Python code***" right after clicking the **Execute** button.

![Capture](https://user-images.githubusercontent.com/36636340/226783703-3358c5f1-7999-4057-b1c4-bcce0f545d4f.PNG)

**Comment by gd3kr** [comment]
I believe it's an OpenAI API key issue. This was resolved in the latest release. Check it out

**Comment by gd3kr** [comment]
Huh. Can you check if the latest release solves the issue? I updated the UI to include a field for the key in the addon preferences

**Comment by Shraknard** [comment]
Nope, exact same error as before. I'm running the latest blender version, added the API key in the filed but still got the "Failed to generate Blender Python code".

**Comment by actualactual** [comment]
Seems I'm stuck with the same issue, was about to pop in here and mention the same thing

**Comment by gd3kr** [comment]
Huh, super weird. I tested with Blender 3.3, and assumed 3.4 would be fine. I'm investigating if it's a 3.4 issue right now. In the meantime, could you check if it works for an earlier version?

**Comment by gd3kr** [comment]
Just checked, works fine on 3.4 as well. Could you paste the stack trace when the error is shown? 
![image](https://user-images.githubusercontent.com/63528145/226792847-3591c1f2-002f-4b0b-b5e1-020426d18af6.png)

**Comment by actualactual** [comment]
here's the error in console
`Warning: 1 x Draw window and swap: 7.0847 ms, average: 7.08470005 ms
INFO:openai:error_code=model_not_found error_message='The model: `gpt-4` does not exist' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False`

**Comment by gd3kr** [comment]
Fixed in the latest release (1 minute ago). It was an issue with GPT-3.5 not being used when the API key does not have access to GPT-4
https://github.com/gd3kr/BlenderGPT/releases/tag/v1.0.2

**Comment by Shraknard** [comment]
Great, it seems to work well now, thanks!
